server:
  port: 80
#é…ç½®eureka
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
